[package]
name = "physics"
version = "0.1.0"
edition = "2024"

[dependencies]
box2d = { path = "../box2d" }
rand = { version = "0.9.2", optional = true }

[features]
default = []
random = ["dep:rand"]